### ISSUE TITLE
can't install because of marisa-trie 0.7.8

### ISSUE THREAD

**Issue by 4nyNoob** [varyg1001/nyaaup#19]
running the install script or a manual install always fails like so: [log.txt](https://github.com/user-attachments/files/15527142/log.txt)
``` 
Installing dependencies from lock file

Package operations: 21 installs, 0 updates, 0 removals

  - Installing marisa-trie (0.7.8)

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  running bdist_wheel
  running build
  running build_clib
  building 'libmarisa-trie' library
  creating build
  creating build/temp.linux-x86_64-cpython-312
  creating build/temp.linux-x86_64-cpython-312/marisa-trie
  creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib
  creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa
  creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire
  creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io
  creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/trie
  creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/vector
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/agent.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/agent.o
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/io/mapper.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/mapper.o
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/io/reader.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/reader.o
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/io/writer.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/writer.o
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/trie/louds-trie.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/trie/louds-trie.o
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/trie/tail.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/trie/tail.o
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/vector/bit-vector.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/vector/bit-vector.o
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/keyset.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/keyset.o
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/trie.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/trie.o
  ar rcs build/temp.linux-x86_64-cpython-312/liblibmarisa-trie.a build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/agent.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/mapper.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/reader.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/writer.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/trie/louds-trie.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/trie/tail.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/vector/bit-vector.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/keyset.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/trie.o
  running build_ext
  building 'marisa_trie' extension
  creating build/temp.linux-x86_64-cpython-312/src
  gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/include -I/tmp/tmpdvsnofkv/.venv/include -I/usr/include/python3.12 -c src/agent.cpp -o build/temp.linux-x86_64-cpython-312/src/agent.o
  src/agent.cpp:6:10: fatal error: Python.h: No such file or directory
      6 | #include "Python.h"
        |          ^~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/gcc' failed with exit code 1
  

  at ~/.local/share/pipx/venvs/poetry/lib64/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with marisa-trie (0.7.8) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "marisa-trie (==0.7.8)"'.

```
and using the command given by the output also spits out an error:  [build.txt](https://github.com/user-attachments/files/15527145/build.txt)
``` 
Collecting marisa-trie==0.7.8
  Downloading marisa-trie-0.7.8.tar.gz (304 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.7/304.7 kB 1.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting setuptools (from marisa-trie==0.7.8)
  File was already downloaded /home/any/anime-web-dl/!tools/nyaaup/setuptools-70.0.0-py3-none-any.whl
Building wheels for collected packages: marisa-trie
  Building wheel for marisa-trie (pyproject.toml): started
  Building wheel for marisa-trie (pyproject.toml): finished with status 'error'
Failed to build marisa-trie

  error: subprocess-exited-with-error

  × Building wheel for marisa-trie (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      running bdist_wheel
      running build
      running build_clib
      building 'libmarisa-trie' library
      creating build
      creating build/temp.linux-x86_64-cpython-312
      creating build/temp.linux-x86_64-cpython-312/marisa-trie
      creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib
      creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa
      creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire
      creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io
      creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/trie
      creating build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/vector
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/agent.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/agent.o
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/io/mapper.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/mapper.o
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/io/reader.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/reader.o
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/io/writer.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/writer.o
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/trie/louds-trie.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/trie/louds-trie.o
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/trie/tail.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/trie/tail.o
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/grimoire/vector/bit-vector.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/vector/bit-vector.o
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/keyset.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/keyset.o
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/lib -Imarisa-trie/include -c marisa-trie/lib/marisa/trie.cc -o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/trie.o
      ar rcs build/temp.linux-x86_64-cpython-312/liblibmarisa-trie.a build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/agent.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/mapper.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/reader.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/io/writer.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/trie/louds-trie.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/trie/tail.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/grimoire/vector/bit-vector.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/keyset.o build/temp.linux-x86_64-cpython-312/marisa-trie/lib/marisa/trie.o
      running build_ext
      building 'marisa_trie' extension
      creating build/temp.linux-x86_64-cpython-312/src
      gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -fPIC -Imarisa-trie/include -I/usr/include/python3.12 -c src/agent.cpp -o build/temp.linux-x86_64-cpython-312/src/agent.o
      src/agent.cpp:6:10: fatal error: Python.h: No such file or directory
          6 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for marisa-trie
ERROR: Failed to build one or more wheels
```

**Comment by varyg1001** [comment]
Oh ye that doesn't work with py 3.12, will update dependencies and will work.
